import { Sun, Rain, Cloud, Snow } from "./Icons";
import { ReactElement } from "react";

const WeatherImages = (size: number): { [key: string]: ReactElement } => ({
  "Sunny": <Sun size={size} />,
  "Clear": <Sun size={size} />,
  "Partly cloudy": <Cloud size={size} />,
  "Cloudy": <Cloud size={size} />,
  "Overcast": <Cloud size={size} />,
  "Mist": <Cloud size={size} />,
  "Fog": <Cloud size={size} />,
  "Patchy rain possible": <Rain size={size} />,
  "Patchy snow possible": <Snow size={size} />,
  "Patchy sleet possible": <Rain size={size} />,
  "Patchy freezing drizzle possible": <Rain size={size} />,
  "Thundery outbreaks possible": <Rain size={size} />,
  "Blowing snow": <Snow size={size} />,
  "Blizzard": <Snow size={size} />,
  "Freezing fog": <Cloud size={size} />,
  "Patchy light drizzle": <Rain size={size} />,
  "Light drizzle": <Rain size={size} />,
  "Freezing drizzle": <Rain size={size} />,
  "Heavy freezing drizzle": <Rain size={size} />,
  "Patchy light rain": <Rain size={size} />,
  "Light rain": <Rain size={size} />,
  "Moderate rain at times": <Rain size={size} />,
  "Moderate rain": <Rain size={size} />,
  "Heavy rain at times": <Rain size={size} />,
  "Heavy rain": <Rain size={size} />,
  "Light freezing rain": <Rain size={size} />,
  "Moderate or heavy freezing rain": <Rain size={size} />,
  "Light sleet": <Rain size={size} />,
  "Moderate or heavy sleet": <Rain size={size} />,
  "Patchy light snow": <Snow size={size} />,
  "Light snow": <Snow size={size} />,
  "Patchy moderate snow": <Snow size={size} />,
  "Moderate snow": <Snow size={size} />,
  "Patchy heavy snow": <Snow size={size} />,
  "Heavy snow": <Snow size={size} />,
  "Ice pellets": <Snow size={size} />,
  "Light rain shower": <Rain size={size} />,
  "Moderate or heavy rain shower": <Rain size={size} />,
  "Torrential rain shower": <Rain size={size} />,
  "Light sleet showers": <Rain size={size} />,
  "Moderate or heavy sleet showers": <Rain size={size} />,
  "Light snow showers": <Snow size={size} />,
  "Moderate or heavy snow showers": <Snow size={size} />,
  "Light showers of ice pellets": <Snow size={size} />,
  "Moderate or heavy showers of ice pellets": <Snow size={size} />,
  "Patchy light rain with thunder": <Rain size={size} />,
  "Moderate or heavy rain with thunder": <Rain size={size} />,
  "Patchy light snow with thunder": <Snow size={size} />,
  "Moderate or heavy snow with thunder": <Snow size={size} />,
});

export default WeatherImages;